GET http://localhost:3000/artists/1
Accept: application/json

###
### Create new user
POST http://localhost:3000/artists
Content-Type: application/json

{
  "firstName": "Ahmed",
  "lastName": "Ayman",
  "email": "ahabdelaziz971@gmail.com",
  "password": "123456"
}

