### Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "Martin",
  "lastName": "Garrix",
  "email": "user12315s6@gmail.com",
  "password": "123456"
}

> {% client.global.set("api_key", response.body.apiKey); %}


### User login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "martingarrix@gmail.com",
  "password": "123456"
}

> {% client.global.set("auth_token", response.body.accessToken); %}

### update user
PATCH http://localhost:3000/auth/update-user
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "oldPassword": "123456",
  "password": "123456"
}


### Get User
GET http://localhost:3000/profile
Content-Type: application/json
Authorization: Bearer {{auth_token}}


### enable-2fa
GET http://localhost:3000/auth/enable-2fa
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### validate-2fa
POST http://localhost:3000/auth/validate-2fa
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "token": "322969"
}

### disable-2fa
GET http://localhost:3000/auth/disable-2fa
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### get profile with api key
GET http://localhost:3000/auth/profile
Content-Type: application/json
Authorization: Bearer d1d69096-39e0-4cc3-863e-16d7f5237e31
